config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :messages
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message

  validates :content, presence: true, length: { maximum: 140 }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :content, presence: true, length: { maximum: 140 }

  paginates_per 3

  has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end

  private

  def user_not_authorized(error)
    flash[:alert] = "Nie masz dostępu do tej akcji!!!"
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:notice] = "Udało się!"
      redirect_to @comment.message
    else
      @message = Message.find(comment_params[:message_id])
      flash[:alert] = "Nie udało się!"
      render 'messages/show'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to @comment
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to message_path(@comment.message)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :author, :message_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = Message.all.page(params[:page])
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to @message
    else
      render :new
    end
  end

  def edit
    @message = Message.find(params[:id])
    authorize(@message)
  end

  def update
    @message = Message.find(params[:id])
    authorize(@message)
    if @message.update(message_params)
      redirect_to @message
    else
      render :edit
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  def destroy
    @message = Message.find(params[:id])
    authorize(@message)
    @message.destroy
    redirect_to messages_path
  end

  private

  def message_params
    params.require(:message).permit(:content, :picture).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<% if comment.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% comment.errors.full_messages.each do |error_msg| %>
        <li><%= error_msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(comment) do |form| %>
  <%= form.hidden_field :message_id, value: message.id %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="actions">
    <%= form.submit "Submit" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= render partial: 'form', locals: { comment: @comment, message: @comment.message } %>

app/views/comments/show.html.erb
<h1><%= @comment.content %></h1>
<h5><%= @comment.author %></h5>

<%= link_to 'Back to message', message_path(@comment.message_id) %>

app/views/home/index.html.erb
<h1>Cvierkacz</h1>

<p>Yet another messaging app</p>

<%= link_to 'List of all messages', messages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cvierkacz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">
      <%= image_tag 'bootstrap-solid.svg', width: 30, height: 30 %>
        Cvierkacz
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span> </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
        <%= link_to "Home", root_path, class: 'nav-link'%> </li>
      </ul>
      <% if user_signed_in? %>
        <span>
          Logged in as
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar.variant(resize: "50x50") %>
          <% end %>
          <strong><%= current_user.email %></strong>.
        </span>
        <%= link_to "Edit", edit_user_registration_path, class: 'btn ml-2' %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-outline-warning ml-2' %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-outline-success my-2 my-sm-0 mr-2' %>
        <%= link_to "Login", new_user_session_path, class: 'btn btn-outline-danger my-2 my-sm-0' %>
      <% end %>
      </div>
    </nav>

    <div class="main">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/messages/_comments.html.erb
<p>
  <strong>Content:</strong>
  <%= comment.content %>
  <%= link_to 'Show', comment %>
  <%= link_to 'Edit', edit_comment_path(comment.id) %>
  <%= link_to 'Delete', comment, method: :delete %>
</p>

app/views/messages/_form.html.erb
<% if message.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% message.errors.full_messages.each do |error_msg| %>
        <li><%= error_msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(message) do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <% if message.picture.attached? %>
    <%= image_tag message.picture.variant(resize: "350x350") %>
  <% end %>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit "Submit" %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<%= render partial: 'form', locals: { message: @message } %>

app/views/messages/index.html.erb
<h1>List of all messages</h1>
<%= link_to 'New message', new_message_path %>

<ul>
  <% @messages.each do |message| %>
    <li>
      <%= message.content %>
      <%= message.user.email %>
      <%= link_to 'Show', message %>
      <% if policy(message).edit? %>
        <%= link_to 'Edit', edit_message_path(message.id) %>
      <% end %>
      <% if policy(message).destroy? %>
        <%= link_to 'Delete', message, method: :delete %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= paginate @messages %>

app/views/messages/new.html.erb
<%= render partial: 'form', locals: { message: @message } %>

app/views/messages/show.html.erb
<h1><%= @message.content %></h1>

<% if @message.picture.attached? %>
  <%= image_tag @message.picture.variant(resize: "350x350") %>
<% end %>

<h5><%= @message.user.email %></h5>

<h3>Add comment</h3>
<%= render partial: 'comments/form', locals: { comment: Comment.new, message: @message } %>

<h3>Comments</h3>
<%= render partial: '/messages/comments', collection: @message.comments, as: :comment %>

<%= link_to 'Back to all messages', messages_path %>